### ISSUE TITLE
failed to run custom build command for `openssl-sys-extras v0.7.14`

### ISSUE THREAD

**Issue by overlisted** [SpaceManiac/discord-rs#165]
I've installed all Linux packages it says on the crate page, but it doesn't compile, with this output: [here](https://gist.github.com/overlisted/e910f1cada79503bace80d726e9cc782)

**Comment by overlisted** [comment]
Maybe that has to do with that I have *a bit* outdated version of rustc installed?

**Comment by SpaceManiac** [comment]
Please use a Git dependency to get the latest updates to discord-rs, which have not been published to crates.io:

```toml
[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
```
