### ISSUE TITLE
Out-Of-Date & Deprecated Dependencies

### ISSUE THREAD

**Issue by JulianDroste** [SpaceManiac/discord-rs#181]
As mentioned in https://github.com/J4YB3/discord-movie-night-bot/issues/60 I checked your dependencies with `cargo audit` and found them to be slightly out of date:

* hyper - >=0.14.10

This can be mitigated by placing the following in `cargo.toml`:
```toml
# ...
[dependencies]
# ...
hyper = { version = ">=0.14.10", default-features = false }
# ...
```

I would also recommend you to divert from the usage of the `net2` crate as it has been deprecated in favor of `socket2`. If you'd like I can open a pull request for the `Cargo.toml` update.
