### ISSUE TITLE
Dj not working?

### ISSUE THREAD

**Issue by AmarOk1412** [SpaceManiac/discord-rs#95]
Hi, I tried the dj.rs example and I can't stream on a voice channel.

The bot join the correct voice channel, so the stream is correct. But voice.play(stream) doesn't stream anything and I don't see any error.

I tried to copy the code in my bot, but I've got `ERROR:discord::voice: Error connecting to voice: Protocol("First voice event was not Handshake")`

**Comment by SpaceManiac** [comment]
Are you using the current master? If not, try this in your `Cargo.toml`:

```toml
[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
```

The current release (`0.7.0`) is a little out of date.
